### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by jordie23** [disqus/disqus-react#86] opened 2020-12-16 23:06 UTC
### Describe the bug  
When using the DiscussionEmbed component this error is generated:

```
Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ReactCompositeComponentWrapper'
    |     property '_instance' -> object with constructor 'App'
    --- property '_reactInternalInstance' closes the circle
    at JSON.stringify (<anonymous>)
    at b.Channel.h.sendMessage (embed.js:44)
    at e.<anonymous> (embed.js:45)
    at e.<anonymous> (embed.js:44)
    at e.<anonymous> (embed.js:44)
    at m (embed.js:44)
    at e.trigger (embed.js:44)
    at e.<anonymous> (embed.js:44)
    at m (embed.js:44)
    at b.Channel.trigger (embed.js:44)
```

It appears that embed.js is trying to stringify the config to use sendMessage, which includes a reference to the DIV container for the discussion, but that includes react references in it which are circular.

### To Reproduce  
  1. Clone this repo 
  2. npm i && npm run build:example && npm start
  3. Navigate to examples, go to an article with a discussion
  4. See error  in console

### Expected behavior  
No error

### Specifications:  
I assume it'd happen on a few platforms but mine specifically are:
 - OS: MacOS 10.15.7
 - Package version: latest
 - Node version: 12
 - Browser: Chrome 87

### Additional context  
Not sure if it's an issue with this package or disqus's embed.js no longer playing nice with react, either way it needs to be solved by disqus.

**Comment by jordie23** [comment] 2020-12-18 04:49
@tterb Sorry to ping you, but I'm hoping you can get this to the right person (if it's not you) at disqus.

**Comment by tterb** [comment] 2020-12-18 05:36
@jordie23 No worries, with the GitHub notification setup sometimes it can be hard to catch when a new issue is opened.
I'll look into this and see if I can track down the cause.

**Comment by Bouhoum** [comment] 2020-12-18 11:53
experiencing the same problem with the gatsby plugin `"gatsby-plugin-disqus": "^1.2.2"` 
throws same error and keep refreshing the page

**Comment by donaldboulton** [comment] 2020-12-18 21:04
Same for me in my Gatsby site with disqus-react not gatsby's plugin, it started after I turned off Auto Site Content in Disqus Admin settings then this error started showing up.
The Auto Site content at the top of Disqus just started showing up yesterday and I turned it off today so something they have does recently.

**Comment by tterb** [comment] 2020-12-18 21:12
@donaldboulton What do you mean by the "Auto Site Content" setting in Disqus Admin?

**Comment by donaldboulton** [comment] 2020-12-19 14:45
At the top of my disqus was a list of my other pages or site content and it displayed the pages in a  carousel display, with a ugly browser scroll bar, and it or disqus had to go.
Turned it off and it was called Auto something and it had to do with enhancements, I am no disqus expert so that's all I can tell ya.
Is and error on publiuslogic.com blog pages, in embed.js And has nothing to do with conflicts or errors in my site.. I have been working on a Content-Security-Policy and paying close attention to console errors and this is new.

error

Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLDivElement'
    |     property '__reactFiber$l85ycptuha' -> object with constructor 'Di'
    --- property 'stateNode' closes the circle
    at JSON.stringify (<anonymous>)
    at b.Channel.h.sendMessage (embed.js:44)
    at e.<anonymous> (embed.js:45)
    at e.<anonymous> (embed.js:44)
    at e.<anonymous> (embed.js:44)
    at m (embed.js:44)
    at e.trigger (embed.js:44)
    at e.<anonymous> (embed.js:44)
    at m (embed.js:44)
    at b.Channel.trigger (embed.js:44)

**Comment by tterb** [comment] 2021-01-04 20:52
I've made the team aware of this issue and we're going to try to track down the cause ASAP.

**Comment by jordie23** [comment] 2021-01-05 00:54
Thanks @tterb ! :)

**Comment by mitchobrian** [comment] 2021-01-14 12:14
> At the top of my disqus was a list of my other pages or site content and it displayed the pages in a carousel display, with a ugly browser scroll bar, and it or disqus had to go.
> Turned it off and it was called Auto something and it had to do with enhancements, I am no disqus expert so that's all I can tell ya.
> Is and error on publiuslogic.com blog pages, in embed.js And has nothing to do with conflicts or errors in my site.. I have been working on a Content-Security-Policy and paying close attention to console errors and this is new.
> 
> error
> 
> Uncaught TypeError: Converting circular structure to JSON
> --> starting at object with constructor 'HTMLDivElement'
> | property '__reactFiber$l85ycptuha' -> object with constructor 'Di'
> --- property 'stateNode' closes the circle
> at JSON.stringify ()
> at b.Channel.h.sendMessage (embed.js:44)
> at e. (embed.js:45)
> at e. (embed.js:44)
> at e. (embed.js:44)
> at m (embed.js:44)
> at e.trigger (embed.js:44)
> at e. (embed.js:44)
> at m (embed.js:44)
> at b.Channel.trigger (embed.js:44)

Same issue on my side:

helpers.js:88 Uncaught TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLDivElement'
    |     property '__reactInternalInstance$h7a2xt4hra4' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
    at JSON.stringify (<anonymous>)
    at b.Channel.h.sendMessage (embed.js:44)
    at e.<anonymous> (embed.js:45)
    at e.<anonymous> (embed.js:44)
    at e.<anonymous> (embed.js:44)
    at m (embed.js:44)
    at e.trigger (embed.js:44)
    at e.<anonymous> (embed.js:44)
    at m (embed.js:44)
    at b.Channel.trigger (embed.js:44)
    at embed.js:44
    at sentryWrapped (helpers.js:72)

Reaching out: https://disqus.com/home/discussion/channel-discussdisqus/bug_reports_feedback_uncaught_typeerror_converting_circular_structure_to_json/#comment-5226867215

**Comment by tterb** [comment] 2021-01-14 17:54
@mitchobrian @jordie23 We have a solution for this issue that will be deployed later today.

**Comment by mitchobrian** [comment] 2021-01-14 18:46
GREAT ! ;)

**Comment by tterb** [comment] 2021-01-14 20:41
The fix just went out, so I would expect that you should stop seeing these issues once the caches clear.
I'm going to leave this issue open for the next couple of days to make sure the problem doesn't persist for anyone and then I'll close it out.

**Comment by mitchobrian** [comment] 2021-01-14 20:58
> The fix just went out, so I would expect that you should stop seeing these issues once the caches clear.
> I'm going to leave this issue open for the next couple of days to make sure the problem doesn't persist for anyone and then I'll close it out.

Good job. Error disappears... What was the problem?

**Comment by tterb** [comment] 2021-01-14 21:08
The issue was related to a recent change that modified the data being passed between the comment thread iframe and the sidebar iframe that is used to show user-profiles and community information. The change indirectly added an attribute that contained an HTMLElement to the data being sent, which when passed to `JSON.stringify()`, resulted in the circular structure error you were seeing.

**Comment by jordie23** [comment] 2021-01-15 02:22
Awesome thanks @tterb ! I can confirm the error has gone from our site too. 👍 I appreciate it a lot!

**Comment by tterb** [comment] 2021-01-25 20:24
I'm gonna close this out since it appears that the issue is resolved for everyone.

**Closed by tterb** 2021-01-25 20:24 UTC
Labels: bug
