### ISSUE TITLE
url wrong: url has two slash so that cannot be directed to the right page.

### ISSUE THREAD

**Issue by Oyyko** [disqus/disqus-react#93] opened 2021-03-25 10:20 UTC
### Describe the bug  

url in `xxx.disqus.com/admin/moderate/approved` has two slash(//), which makes it unable to render the comment area. Besides, when using shared links, the same reason will make a same trouble. For more detials, please see [here](https://github.com/crystal-lang/crystal-website/issues/62) and [here](https://github.com/casbin/casbin-website/issues/193).

### To Reproduce  
  1. Go to `casbin.org` or `crystal-lang.org`
  2. leave a comment using disqus
  3. copy share link
  4. open share link
  5. The url will have two slash. For example: `casbin.org//xxx/yyy/zz`

### Expected behavior  

The url should have only one slash. For example: "xxxxx.org/yy/zz"

### Screenshots  

Please see the two PRs above.

**Comment by tterb** [comment] 2021-03-30 17:59
@Oyyko In the meantime, it looks like the share-links can be fixed by the site-owner by removing the backslash from the end of the **Website URL** at https://crystal-lang.disqus.com/admin/settings/general/

**Comment by Oyyko** [comment] 2021-04-01 15:09
Thanks for your attention. However, I tried to remove the backslash but it seems that nothing happened. Really a strange bug.

**Comment by lacardonap** [comment] 2021-04-09 22:17
I don't know if this is the right place, but I want to share a gif that shows how leaving two slashes in on the main page causes the page to reload infinitely.

Tested: 
Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)
Mozilla Firefox Version 87.0 (64-bit)
![infi_reload_page](https://user-images.githubusercontent.com/8827336/114246093-5f006d00-9957-11eb-8688-0877eb24f916.gif)

**Comment by hsluoyz** [comment] 2021-04-23 15:39
> @Oyyko In the meantime, it looks like the share-links can be fixed by the site-owner by removing the backslash from the end of the **Website URL** at https://crystal-lang.disqus.com/admin/settings/general/

@tterb our URL was already without ending slash

![image](https://user-images.githubusercontent.com/3787410/115895497-12f01500-a48d-11eb-88a3-8216310bb4b9.png)

**Comment by hsluoyz** [comment] 2021-07-09 14:54
Hi @tterb , any update on the double slashes issue?

**Comment by tterb** [comment] 2021-07-12 17:47
@hsluoyz @Oyyko A member of our support team investigated this issue and found that the reason for the double-slashes in URLs is a result of the `url` that is being set in the `disqus_config` containing double-slashes.

You can fix the issue on existing threads by updating the thread URLs using the [URL Mapper](https://help.disqus.com/en/articles/1717129-url-mapper) and prevent the issue from occurring on new threads by ensuring the correct URL is being set in your `disqus_config`.

**Comment by hsluoyz** [comment] 2021-07-13 08:58
Hi @tterb , thanks for your reply! About this part:

>  prevent the issue from occurring on new threads by ensuring the correct URL is being set in your disqus_config.

I think we don't have double slashes in our config: https://github.com/casbin/casbin-website/blob/master/website/static/js/disqus.js But it's still happening on new threads. Why?

```js
const PAGE_IDENTIFIER = window.location.pathname;
const BASE_URL = 'https://casbin.org';
const PAGE_URL = BASE_URL + PAGE_IDENTIFIER;

/**
 *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
 */
var disqus_config = function() {
  this.page.url = PAGE_URL; // Page's canonical URL variable
  this.page.identifier = PAGE_IDENTIFIER; // Page's unique identifier variable
};

function loadDisqus() {
  (function() {
    // DON'T EDIT BELOW THIS LINE
    s = document.createElement('script');
    s.src = 'https://casbin.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (document.head || document.body).appendChild(s);
  })();
}

function maybeLoadDisqus() {
  const hr = document.createElement('hr');
  const disqusContainer = document.createElement('disqus');
  disqusContainer.id = 'disqus_thread';
  const postContainer = document.querySelectorAll('.post article')[0];
  const isDocsPage = PAGE_IDENTIFIER.indexOf('/docs') !== -1;
  if (postContainer && isDocsPage) {
    postContainer.appendChild(hr);
    postContainer.appendChild(disqusContainer);
    loadDisqus();
  }
  // editor page
  if (PAGE_IDENTIFIER.indexOf('/editor') !== -1) {
    var el = document.getElementById('disqus');
    el.appendChild(hr);
    el.appendChild(disqusContainer);
    loadDisqus();
  }
}

document.addEventListener('DOMContentLoaded', function() {
  maybeLoadDisqus();
});
```

**Comment by ErikQQY** [comment] 2021-07-13 17:13
@hsluoyz I am trying to solve this issue

**Comment by tterb** [comment] 2021-07-13 17:35
I don't see an issue in the above code snippet that would cause new threads to have double backslashes in the URL and I'm not seeing any incorrectly formatted URLs at https://casbin.disqus.com/admin/discussions/.

Though, I did find the issue in `crystal-lang.org` [here](https://github.com/crystal-lang/crystal-website/blob/af07adfccb686e5890b2dd6f687458d55eede2a6/_layouts/post.html#L41) as the `page.url` begins with backslash.

**Comment by hsluoyz** [comment] 2021-07-14 06:17
@tterb but for this page: https://casbin.disqus.com/admin/moderate/approved , you can see the double slashes here:

![image](https://user-images.githubusercontent.com/3787410/125572569-150bc739-9597-40c0-93c3-fea2b8db1a03.png)

**Comment by tterb** [comment] 2021-07-16 19:02
@hsluoyz Is that a thread that you've already updated the URL for using the [URL Mapper](https://help.disqus.com/en/articles/1717129-url-mapper) I mentioned earlier?
Also, could you provide a link to a newly created thread where you're seeing the issue?

**Comment by ErikQQY** [comment] 2021-07-26 03:41
@tterb Thanks for your help, I have already updated the URL using URL Mapper, the issue is now solved.

Besides, when I use the URL Mapper, the csv file containing comments doesn't covers all of our comments, so I have to edit some links directly in admin portal.

**Comment by hsluoyz** [comment] 2021-07-26 03:45
@tterb thanks for the help! I confirmed that the issue has been fixed. Feel free to close this issue :)

**Closed** 2021-08-09 20:45 UTC
