### ISSUE TITLE
Component style not updating

### ISSUE THREAD

**Issue by neohed** [disqus/disqus-react#34] opened 2019-07-24 19:52 UTC
Hi,
I'm using disqus-react with this [gatsbyjs starter project](https://github.com/eggheadio/gatsby-starter-egghead-blog)

The problem is when I use the theme switcher the styles for disqus-react don't update without a page refresh.  I tried passing the theme name into react-disqus as a prop to force an update but that didn't work:

`<DiscussionEmbed theme={themeName} shortname={disqusShortname} config={disqusConfig} />`

Any thoughts on how to force the styles to update?

**Comment by tterb** [comment] 2019-07-29 17:06
@neohed I'll look into trying to reproduce this today with the gatsby starter and see if there's a viable solution or if the component can be updated to accommodate style changes.

**Comment by tterb** [comment] 2019-07-29 23:40
@neohed I was able to reproduce this issue, and it looks like passing the theme name wasn't forcing an update because the `DiscussionEmbed` components `shouldComponentUpdate` method is only checking for changes in specific props.

I've created a [PR](https://github.com/disqus/disqus-react/pull/35) that I think should address your issue, if you want to test it out and confirm.

**Comment by neohed** [comment] 2019-07-30 08:12
@tterb I ran a test just now but still see the same issue. I'll test this more later to confirm...

**Comment by tterb** [comment] 2019-07-30 16:57
@neohed Just to clarify, the PR #35 hasn't been merged/published yet so you won't see an  changes unless you pull from that branch and use the local package in the gatsby-starter, instead of the published version from npm.  
I just wanted to ensure that the changes fixed your issue before merging it and publishing a new version.

**Comment by neohed** [comment] 2019-08-03 09:12
@tterb Thanks for clarifying and for your work on this - it is appreciated. I did pull from the PR branch into a local repo but then didn't know how to import that into my gatsby site. I tried import from the filepath but got compile errors - it seemed like webpack was trying to resolve gatsby dependencies in disqus-react...?

**Comment by tterb** [comment] 2019-08-03 22:13
@neohed The easiest way to test the PR locally would be to pull the branch into a local `disqus-react` directory that is in the same parent directory as your `gatsby-starter-egghead-blog/` repo. Then you can `cd` into your gatsby starter and create a [symlink](https://yarnpkg.com/lang/en/docs/cli/link/) to the local package with the command:
```sh
yarn link ../disqus-react
```

**Comment by neohed** [comment] 2019-08-04 11:59
@tterb cool symlink worked great - I learned something new!  And your fix does work. It updates correctly.  What I'm seeing here now seems to be a different bug with my gatsby site where the themeName inside post.js is always "default" even when using "dark" theme...  But that's unrelated to disqus-react.

I can confirm your fix works.  Thanks.

**Comment by tterb** [comment] 2019-08-05 04:31
@neohed I'm glad we were able to your fix your issue and I appreciate your responsiveness in providing feedback to help improve the package 👍   

I'll merge #35 tomorrow and get a patch published to npm.

**Closed** 2019-08-09 22:59 UTC
Labels: bug
