### ISSUE TITLE
Cannot read property 'forumsFollowing' of undefined

### ISSUE THREAD

**Issue by DanielW093** [disqus/disqus-react#36] opened 2019-08-05 08:44 UTC
### Describe the bug  
I'm not sure what the root cause of this bug is, but sometimes (often) when I try clicking the button on the Disqus component that opens the Disqus overlay, I get the error `Cannot read property 'forumsFollowing' of undefined` in my console. At this point nothing happens, but I cannot interact with my page any longer due to the error.

### To Reproduce  
It's happening just when the component loads, and I click the button next to the comment count that opens the overlay for my forum.

**EDIT**
On closer investigation, this bug appears to occur as a result of a button I have to load the discussion thread. If the component loads on start, it works fine, but if I have a conditional rendering that causes the discussion thread to only load when I click a button, then loading the overlay creates this bug. The conditional render looks like this:

```
        if(this.state.displayComments && this.state.disqusConfig) {
            const disqusConfig = this.state.disqusConfig;
            return <DiscussionEmbed shortname={disqusConfig.disqusShortName} config={disqusConfig.config} />;
        }

        return (
            <div className={styles.commentsButton}>
             <Button onClick={() => {this.setState({displayComments: true})}}>Load Comments</Button>
            </div>
        )
```

**EDIT 2** 
The issue doesn't seem to be exclusive to the above scenario after all. 

### Expected behavior  
The forum overlay opens without any errors.

**Comment by tterb** [comment] 2019-08-05 17:15
@DanielW093 Thanks for providing detailed description and reproduction info.  
While the described configuration isn't recommended, I will look into trying to reproduce this issue and track down whether it's something that can be fixed within the scope of this package.

**Comment by DanielW093** [comment] 2019-08-05 17:28
@tterb No problem! I'm actually able to reproduce it even when it's just in my component with none of that extra stuff going on, but I'm not 100% sure of the cause.

**Comment by DanielW093** [comment] 2019-08-05 20:15
@tterb If you'd like to reproduce it running in production, you can go to:
https://candywool-games.github.io/blog/posts/bloop-bleep

And click the "Load Comments" button at the bottom, then try opening the overlay.

**Comment by tterb** [comment] 2019-08-05 22:45
@DanielW093 I was able to recreate the issue both with and without having the component behind a button, so I'll continue looking into this further and try to track down the cause.

**Comment by DanielW093** [comment] 2019-08-06 09:52
That's good news! I feel better about using the package in its current state knowing that this bug exists in the service itself.

**Comment by tterb** [comment] 2019-08-08 22:56
@DanielW093 We appreciate you bringing this issue to our attention, a fix has been merged and will be deployed shortly.

**Closed by tterb** 2019-08-08 22:56 UTC
Labels: bug

**Comment by braindeaf** [comment] 2019-09-07 12:28
Can you explain how you solved this problem. I'm trying to solve the same error with lightGallery and it's lg-comment solution, which appears to move and reset disqus_thread on each change. Considering trying to use disqus-react as a replacement for their solution. If it makes it simpler to load comments.

**Comment by tterb** [comment] 2019-09-07 20:38
@braindeaf The source of this issue was a problem with the way the main Disqus embedded comments section was opening the forum overlay. This shouldn't be an error that can be caused by the implementation of an external package.
